apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  creationTimestamp: null
  name: lvm-metrics
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: lvm-metrics
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: openshift-monitoring
