apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/compose: metrics
  name: topolvm-node-metrics
spec:
  ports:
  - name: topolvm-metrics
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.lvm.openshift.io: topolvm-node
status:
  loadBalancer: {}
