apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: topolvm-node-scc
rules:
- apiGroups:
  - security.openshift.io
  resourceNames:
  - topolvm-node
  resources:
  - securitycontextconstraints
  verbs:
  - use
