# permissions for end users to edit lvmvolumegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvmvolumegroup-editor-role
rules:
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroups
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroups/status
  verbs:
  - get
