# permissions for end users to view lvmvolumegroupnodestatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvmvolumegroupnodestatus-viewer-role
rules:
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroupnodestatuses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroupnodestatuses/status
  verbs:
  - get
