# permissions for end users to edit lvmvolumegroupnodestatuses.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvmvolumegroupnodestatus-editor-role
rules:
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroupnodestatuses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroupnodestatuses/status
  verbs:
  - get
