# permissions for end users to view lvmvolumegroups.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: lvmvolumegroup-viewer-role
rules:
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroups
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - lvm.topolvm.io
  resources:
  - lvmvolumegroups/status
  verbs:
  - get
