kind: SecurityContextConstraints
apiVersion: security.openshift.io/v1
metadata:
  name: topolvm-node
  annotations:
    kubernetes.io/description: 'topolvm-node allows access to host
        features and the ability to run as any user, any group, any fsGroup, and with
        any SELinux context. Use this SCC only for topolvm node daemonset'
allowHostDirVolumePlugin: true # Needed for volumes
allowHostIPC: false
allowHostNetwork: false
allowHostPID: true  # lvmd needs to see pid 1
allowHostPorts: false
allowPrivilegeEscalation: true  # topolvm node uses privileged containers
allowPrivilegedContainer: true
readOnlyRootFilesystem: false
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
volumes:
  - 'configMap'
  - 'emptyDir'
  - 'secret'
  - 'hostPath'
